export const GET_PROJECT_REQUEST= "GET_PROJECT_REQUEST" 
export const GET_PROJECT_SUCCESS= "GET_PROJECT_SUCCESS" 
export const GET_PROJECT_FAIL= "GET_PROJECT_FAIL" 

export const ADD_PROJECT_REQUEST= "ADD_PROJECT_REQUEST" 
export const ADD_PROJECT_SUCCESS= "GET_PROJECT_SUCCESS" 
export const ADD_PROJECT_FAIL= "ADD_PROJECT_FAIL" 
export const ADD_PROJECT_RESET= "ADD_PROJECT_RESET" 

export const DETAIL_PROJECT_REQUEST= "DETAIL_PROJECT_REQUEST" 
export const DETAIL_PROJECT_SUCCESS= "DETAIL_PROJECT_SUCCESS" 
export const DETAIL_PROJECT_FAIL= "DETAIL_PROJECT_FAIL" 

export const UPDATE_PROJECT_REQUEST= "UPDATE_PROJECT_REQUEST" 
export const UPDATE_PROJECT_SUCCESS= "UPDATE_PROJECT_SUCCESS" 
export const UPDATE_PROJECT_FAIL= "UPDATE_PROJECT_FAIL" 

export const DELETE_PROJECT_REQUEST= "DELETE_PROJECT_REQUEST" 
export const DELETE_PROJECT_SUCCESS= "DELETE_PROJECT_SUCCESS" 
export const DELETE_PROJECT_FAIL= "DELETE_PROJECT_FAIL"

export const SIGNUP_PROJECT_REQUEST= "SIGNUP_PROJECT_REQUEST" 
export const SIGNUP_PROJECT_SUCCESS= "SIGNUP_PROJECT_SUCCESS" 
export const SIGNUP_PROJECT_FAIL= "SIGNUP_PROJECT_FAIL" 

export const LOGIN_PROJECT_REQUEST= "LOGIN_PROJECT_REQUEST" 
export const LOGIN_PROJECT_SUCCESS= "LOGIN_PROJECT_SUCCESS" 
export const LOGIN_PROJECT_FAIL= "LOGIN_PROJECT_FAIL"

export const LOGOUT_PROJECT= "LOGOUT_PROJECT"


